apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
helmGlobals:
  chartHome: ../../../helm-charts
helmCharts:
  - name: common-apps
    releaseName: app1
    namespace: default
    valuesFile: values.yaml
