apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: standard
spec:
  generators:
    - git:
        repoURL: https://github.com/michaelchee-aeon360/k8s-example.git
        revision: main
        directories:
          - path: k8s/apps/*/prod
  template:
    metadata:
      name: "{{ index .path.segments 2 }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelchee-aeon360/k8s-example.git
        targetRevision: main
        path: "{{ path.path }}"
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
