global:
  nodeSelector:
    cloud.google.com/compute-class: default-class
commonLabels:
  app: external-secrets
serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@aeon360-prod-data-01.iam.gserviceaccount.com
