apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    repo: https://charts.external-secrets.io/
    version: 1.2.1
    includeCRDs: true
    valuesFile: ../base/values.yaml
    valuesInline:
      serviceAccount:
        annotations:
          iam.gke.io/gcp-service-account: external-secrets@aeon360-dev-data-01.iam.gserviceaccount.com
