apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./applicationsets

helmCharts:
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    repo: https://argoproj.github.io/argo-helm
    version: 9.2.4
    includeCRDs: true
    valuesFile: values.yaml
