name: Terragrunt Apply

on:
  push:
    branches: [main]
    paths:
      - "terragrunt/**"

concurrency:
  group: terragrunt-apply
  cancel-in-progress: false

jobs:
  format-validation-plan:
    name: Main Format Checks, Validation, and Plan
    uses: ./.github/workflows/terragrunt-reuse-plan.yaml
    with:
      run_type: main
  apply:
    name: Terragrunt Apply
    runs-on: ubuntu-latest
    container:
      image: devopsinfra/docker-terragrunt:tf-1.14.3-tg-0.97.2
    environment: production
    needs: format-validation-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fix dubious ownership
        run: git config --global --add safe.directory '*'
      - name: Terragrunt
        run: echo "Terragrunt Apply"
        # run: terragrunt run --all --filter "[HEAD~1...HEAD]" apply
