name: Terragrunt Apply

on:
  push:
    branches: [main]
    paths:
      - "terragrunt/**"

concurrency:
  group: terragrunt-apply
  cancel-in-progress: false

jobs:
  format-validation-plan:
    name: Main Format Checks, Validation, and Plan
    uses: ./.github/workflows/terragrunt-reuse-plan.yaml
  apply:
    name: Terragrunt Apply
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:1.14.1
    defaults:
      run:
        working-directory: ./terragrunt/environments
    environment: production
    needs: format-validation-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Terragrunt
        run: echo "Terragrunt Apply"
        # run: terragrunt run --all apply
