name: Terragrunt Apply

on:
  push:
    branches: [main]
    paths:
      - "terragrunt/**"

concurrency:
  group: terragrunt-apply-main
  cancel-in-progress: false

jobs:
  format-validation-plan:
    name: Run Terraform and Terragrunt Format Checks, Validation, and Plan
    uses: ./.github/workflows/terragrunt-reuse-plan.yaml
  apply:
    name: Run Terragrunt Apply
    runs-on: ubuntu-latest
    container:
      image: alpine/terragrunt:1.14.1
    defaults:
      run:
        working-directory: ./terragrunt/environments
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Terragrunt
        run: echo "Terragrunt Apply"
        # run: terragrunt run --all apply
